MainMissionID: u32,
Type: []const u8,
IsLoop: bool,
NextMainMissionList: []const u32,
TakeType: []const u8,
TakeParamInt1: u32,
TakeParamIntList: []const u32,
BeginType: []const u8,
BeginParamInt1: u32,
BeginParamIntList: []const u32,
StartSubMissionList: []const u32,
FinishSubMissionList: []const u32,
NextTrackMainMission: u32,
TrackWeight: u32,
RewardID: u32,
